#pragma once
#include <BNMIncludes.hpp>
#include <BNMResolve.hpp>
#include "../ForwardDeclarations.hpp"

namespace GorillaTagScripts_VirtualStumpCustomMaps_UI {
    enum class CustomMapKeyboardBinding : int {
        zero = 0,
        one = 1,
        two = 2,
        three = 3,
        four = 4,
        five = 5,
        six = 6,
        seven = 7,
        eight = 8,
        nine = 9,
        up = 10,
        down = 11,
        $delete = 12,
        enter = 13,
        option1 = 14,
        option2 = 15,
        option3 = 16,
        A = 17,
        B = 18,
        C = 19,
        D = 20,
        E = 21,
        F = 22,
        G = 23,
        H = 24,
        I = 25,
        J = 26,
        K = 27,
        L = 28,
        M = 29,
        N = 30,
        O = 31,
        P = 32,
        Q = 33,
        R = 34,
        S = 35,
        T = 36,
        U = 37,
        V = 38,
        W = 39,
        X = 40,
        Y = 41,
        Z = 42,
        at = 43,
        dash = 44,
        period = 45,
        underscore = 46,
        plus = 47,
        space = 48,
        goback = 49,
        left = 50,
        right = 51,
        option4 = 52,
        sort = 53,
        sub = 54,
        map = 55,
        all = 56,
        fav = 57,
        inst = 58,
        mustplay = 59,
        rateUp = 60,
        rateDown = 61,
        tile1 = 62,
        tile2 = 63,
        tile3 = 64,
        tile4 = 65,
        tile5 = 66,
        tile6 = 67,
        tile7 = 68,
        tile8 = 69,
        tile9 = 70,
    };
}
