#pragma once
#include <BNMIncludes.hpp>
#include <BNMResolve.hpp>
#include "../ForwardDeclarations.hpp"

namespace GlobalNamespace {
    struct GorillaTelemetry_k : BNM::UnityEngine::MonoBehaviour {
    public:
        static BNM::Class GetClass() {
            static BNM::Class clazz = ::BNM::Class("", "GorillaTelemetry").GetInnerClass("k");
            return clazz;
        }

        static BNM::MonoType* GetType() { return GetClass().GetMonoType(); }

        static constexpr const char* User = "User";
        static constexpr const char* ZoneId = "ZoneId";
        static constexpr const char* SubZoneId = "SubZoneId";
        static constexpr const char* EventType = "EventType";
        static constexpr const char* IsPrivateRoom = "IsPrivateRoom";
        static constexpr const char* Items = "Items";
        static constexpr const char* VoiceChatEnabled = "VoiceChatEnabled";
        static constexpr const char* JoinGroups = "JoinGroups";
        static constexpr const char* CustomUsernameEnabled = "CustomUsernameEnabled";
        static constexpr const char* AgeCategory = "AgeCategory";
        static constexpr const char* telemetry_zone_event = "telemetry_zone_event";
        static constexpr const char* telemetry_shop_event = "telemetry_shop_event";
        static constexpr const char* telemetry_kid_event = "telemetry_kid_event";
        static constexpr const char* telemetry_ggwp_event = "telemetry_ggwp_event";
        static constexpr const char* NOTHING = "NOTHING";
        static constexpr const char* telemetry_wam_gameStartEvent = "telemetry_wam_gameStartEvent";
        static constexpr const char* telemetry_wam_levelEndEvent = "telemetry_wam_levelEndEvent";
        static constexpr const char* WamMachineId = "WamMachineId";
        static constexpr const char* WamGameId = "WamGameId";
        static constexpr const char* WamMLevelNumber = "WamMLevelNumber";
        static constexpr const char* WamGoodMolesShown = "WamGoodMolesShown";
        static constexpr const char* WamHazardMolesShown = "WamHazardMolesShown";
        static constexpr const char* WamLevelMinScore = "WamLevelMinScore";
        static constexpr const char* WamLevelScore = "WamLevelScore";
        static constexpr const char* WamHazardMolesHit = "WamHazardMolesHit";
        static constexpr const char* WamGameState = "WamGameState";
        static constexpr const char* CustomMapName = "CustomMapName";
        static constexpr const char* LowestFPS = "LowestFPS";
        static constexpr const char* LowestFPSDrawCalls = "LowestFPSDrawCalls";
        static constexpr const char* LowestFPSPlayerCount = "LowestFPSPlayerCount";
        static constexpr const char* AverageFPS = "AverageFPS";
        static constexpr const char* AverageDrawCalls = "AverageDrawCalls";
        static constexpr const char* AveragePlayerCount = "AveragePlayerCount";
        static constexpr const char* HighestFPS = "HighestFPS";
        static constexpr const char* HighestFPSDrawCalls = "HighestFPSDrawCalls";
        static constexpr const char* HighestFPSPlayerCount = "HighestFPSPlayerCount";
        static constexpr const char* CustomMapCreator = "CustomMapCreator";
        static constexpr const char* CustomMapModId = "CustomMapModId";
        static constexpr const char* MinPlayerCount = "MinPlayerCount";
        static constexpr const char* MaxPlayerCount = "MaxPlayerCount";
        static constexpr const char* PlaytimeOnMap = "PlaytimeOnMap";
        static constexpr const char* PlaytimeInSeconds = "PlaytimeInSeconds";
        static constexpr const char* PrivateRoom = "PrivateRoom";
        static constexpr const char* ghost_game_start = "ghost_game_start";
        static constexpr const char* ghost_game_end = "ghost_game_end";
        static constexpr const char* ghost_floor_start = "ghost_floor_start";
        static constexpr const char* ghost_floor_end = "ghost_floor_end";
        static constexpr const char* ghost_tool_purchased = "ghost_tool_purchased";
        static constexpr const char* ghost_game_rank_up = "ghost_game_rank_up";
        static constexpr const char* ghost_game_tool_unlock = "ghost_game_tool_unlock";
        static constexpr const char* ghost_pod_upgrade_purchased = "ghost_pod_upgrade_purchased";
        static constexpr const char* ghost_game_tool_upgrade = "ghost_game_tool_upgrade";
        static constexpr const char* ghost_chaos_seed_start = "ghost_chaos_seed_start";
        static constexpr const char* ghost_chaos_juice_collected = "ghost_chaos_juice_collected";
        static constexpr const char* ghost_overdrive_purchased = "ghost_overdrive_purchased";
        static constexpr const char* ghost_credits_refill_purchased = "ghost_credits_refill_purchased";
        static constexpr const char* ghost_game_id = "ghost_game_id";
        static constexpr const char* event_timestamp = "event_timestamp";
        static constexpr const char* initial_cores_balance = "initial_cores_balance";
        static constexpr const char* final_cores_balance = "final_cores_balance";
        static constexpr const char* cores_spent_waiting_in_breakroom = "cores_spent_waiting_in_breakroom";
        static constexpr const char* cores_collected = "cores_collected";
        static constexpr const char* cores_collected_from_ghosts = "cores_collected_from_ghosts";
        static constexpr const char* cores_collected_from_gathering = "cores_collected_from_gathering";
        static constexpr const char* cores_spent_on_items = "cores_spent_on_items";
        static constexpr const char* cores_spent_on_gates = "cores_spent_on_gates";
        static constexpr const char* cores_spent_on_levels = "cores_spent_on_levels";
        static constexpr const char* cores_given_to_others = "cores_given_to_others";
        static constexpr const char* cores_received_from_others = "cores_received_from_others";
        static constexpr const char* gates_unlocked = "gates_unlocked";
        static constexpr const char* died = "died";
        static constexpr const char* caught_in_anamole = "caught_in_anamole";
        static constexpr const char* items_purchased = "items_purchased";
        static constexpr const char* levels_unlocked = "levels_unlocked";
        static constexpr const char* shift_cut = "shift_cut";
        static constexpr const char* number_of_players = "number_of_players";
        static constexpr const char* start_at_beginning = "start_at_beginning";
        static constexpr const char* seconds_into_shift_at_join = "seconds_into_shift_at_join";
        static constexpr const char* reason = "reason";
        static constexpr const char* play_duration = "play_duration";
        static constexpr const char* started_late = "started_late";
        static constexpr const char* time_started = "time_started";
        static constexpr const char* max_number_in_game = "max_number_in_game";
        static constexpr const char* end_number_in_game = "end_number_in_game";
        static constexpr const char* items_picked_up = "items_picked_up";
        static constexpr const char* super_infection_room_disconnect = "super_infection_room_disconnect";
        static constexpr const char* super_infection_interval = "super_infection_interval";
        static constexpr const char* super_infection_purchase = "super_infection_purchase";
        static constexpr const char* si_purchase_type = "si_purchase_type";
        static constexpr const char* si_shiny_rock_cost = "si_shiny_rock_cost";
        static constexpr const char* si_tech_points_purchased = "si_tech_points_purchased";
        static constexpr const char* total_play_time = "total_play_time";
        static constexpr const char* room_play_time = "room_play_time";
        static constexpr const char* session_play_time = "session_play_time";
        static constexpr const char* interval_play_time = "interval_play_time";
        static constexpr const char* terminal_total_time = "terminal_total_time";
        static constexpr const char* terminal_interval_time = "terminal_interval_time";
        static constexpr const char* time_holding_gadget_type_total = "time_holding_gadget_type_total";
        static constexpr const char* time_holding_gadget_type_interval = "time_holding_gadget_type_interval";
        static constexpr const char* time_holding_own_gadgets_total = "time_holding_own_gadgets_total";
        static constexpr const char* time_holding_own_gadgets_interval = "time_holding_own_gadgets_interval";
        static constexpr const char* time_holding_others_gadgets_total = "time_holding_others_gadgets_total";
        static constexpr const char* time_holding_others_gadgets_interval = "time_holding_others_gadgets_interval";
        static constexpr const char* tags_holding_gadget_type_total = "tags_holding_gadget_type_total";
        static constexpr const char* tags_holding_gadget_type_interval = "tags_holding_gadget_type_interval";
        static constexpr const char* tags_holding_own_gadgets_total = "tags_holding_own_gadgets_total";
        static constexpr const char* tags_holding_own_gadgets_interval = "tags_holding_own_gadgets_interval";
        static constexpr const char* tags_holding_others_gadgets_total = "tags_holding_others_gadgets_total";
        static constexpr const char* tags_holding_others_gadgets_interval = "tags_holding_others_gadgets_interval";
        static constexpr const char* resource_collected_total = "resource_collected_total";
        static constexpr const char* resource_collected_interval = "resource_collected_interval";
        static constexpr const char* rounds_played_total = "rounds_played_total";
        static constexpr const char* rounds_played_interval = "rounds_played_interval";
        static constexpr const char* unlocked_nodes = "unlocked_nodes";
        static constexpr const char* floor_joined = "floor_joined";
        static constexpr const char* player_rank = "player_rank";
        static constexpr const char* total_cores_collected_by_player = "total_cores_collected_by_player";
        static constexpr const char* total_cores_collected_by_group = "total_cores_collected_by_group";
        static constexpr const char* total_cores_spent_by_player = "total_cores_spent_by_player";
        static constexpr const char* total_cores_spent_by_group = "total_cores_spent_by_group";
        static constexpr const char* floor = "floor";
        static constexpr const char* preset = "preset";
        static constexpr const char* modifier = "modifier";
        static constexpr const char* section = "section";
        static constexpr const char* xp_gained = "xp_gained";
        static constexpr const char* chaos_seeds_collected = "chaos_seeds_collected";
        static constexpr const char* objectives_completed = "objectives_completed";
        static constexpr const char* revives = "revives";
        static constexpr const char* tool = "tool";
        static constexpr const char* tool_level = "tool_level";
        static constexpr const char* cores_spent = "cores_spent";
        static constexpr const char* shiny_rocks_spent = "shiny_rocks_spent";
        static constexpr const char* new_rank = "new_rank";
        static constexpr const char* upgrade = "upgrade";
        static constexpr const char* grift_price = "grift_price";
        static constexpr const char* type = "type";
        static constexpr const char* new_level = "new_level";
        static constexpr const char* juice_spent = "juice_spent";
        static constexpr const char* grift_spent = "grift_spent";
        static constexpr const char* chaos_seeds_in_queue = "chaos_seeds_in_queue";
        static constexpr const char* unlock_time = "unlock_time";
        static constexpr const char* shiny_rocks_used = "shiny_rocks_used";
        static constexpr const char* juice_collected = "juice_collected";
        static constexpr const char* cores_processed_by_overdrive = "cores_processed_by_overdrive";
        static constexpr const char* final_credits = "final_credits";
        static constexpr const char* is_private_room = "is_private_room";
        static constexpr const char* num_shifts_played = "num_shifts_played";
        static constexpr const char* game_mode_played_event = "game_mode_played_event";
        static constexpr const char* game_mode = "game_mode";
    };
}
