#pragma once
#include <BNMIncludes.hpp>
#include <BNMResolve.hpp>
#include "../ForwardDeclarations.hpp"

namespace GorillaNetworking {
    enum class GorillaKeyboardBindings : int {
        zero = 0,
        one = 1,
        two = 2,
        three = 3,
        four = 4,
        five = 5,
        six = 6,
        seven = 7,
        eight = 8,
        nine = 9,
        up = 10,
        down = 11,
        $delete = 12,
        enter = 13,
        option1 = 14,
        option2 = 15,
        option3 = 16,
        A = 17,
        B = 18,
        C = 19,
        D = 20,
        E = 21,
        F = 22,
        G = 23,
        H = 24,
        I = 25,
        J = 26,
        K = 27,
        L = 28,
        M = 29,
        N = 30,
        O = 31,
        P = 32,
        Q = 33,
        R = 34,
        S = 35,
        T = 36,
        U = 37,
        V = 38,
        W = 39,
        X = 40,
        Y = 41,
        Z = 42,
    };
}
