#pragma once
#include <BNMIncludes.hpp>
#include <BNMResolve.hpp>
#include "../ForwardDeclarations.hpp"

namespace GorillaTag_CosmeticSystem {
    enum class GTHardCodedBones_EBone : int {
        None = 0,
        rig = 1,
        body = 2,
        head = 3,
        head_end = 4,
        shoulder_L = 5,
        upper_arm_L = 6,
        forearm_L = 7,
        hand_L = 8,
        palm_01_L = 9,
        palm_02_L = 10,
        thumb_01_L = 11,
        thumb_02_L = 12,
        thumb_03_L = 13,
        thumb_03_L_end = 14,
        f_index_01_L = 15,
        f_index_02_L = 16,
        f_index_03_L = 17,
        f_index_03_L_end = 18,
        f_middle_01_L = 19,
        f_middle_02_L = 20,
        f_middle_03_L = 21,
        f_middle_03_L_end = 22,
        shoulder_R = 23,
        upper_arm_R = 24,
        forearm_R = 25,
        hand_R = 26,
        palm_01_R = 27,
        palm_02_R = 28,
        thumb_01_R = 29,
        thumb_02_R = 30,
        thumb_03_R = 31,
        thumb_03_R_end = 32,
        f_index_01_R = 33,
        f_index_02_R = 34,
        f_index_03_R = 35,
        f_index_03_R_end = 36,
        f_middle_01_R = 37,
        f_middle_02_R = 38,
        f_middle_03_R = 39,
        f_middle_03_R_end = 40,
        body_AnchorTop_Neck = 41,
        body_AnchorFront_StowSlot = 42,
        body_AnchorFrontLeft_Badge = 43,
        body_AnchorFrontRight_NameTag = 44,
        body_AnchorBack = 45,
        body_AnchorBackLeft_StowSlot = 46,
        body_AnchorBackRight_StowSlot = 47,
        body_AnchorBottom = 48,
        body_AnchorBackBottom_Tail = 49,
        hand_L_AnchorBack = 50,
        hand_R_AnchorBack = 51,
        hand_L_AnchorFront_GameModeItemSlot = 52,
    };
}
